version: "3"
services:
  mqtt-broker:
    build:
      context: .
      dockerfile: Dockerfile-mosquitto
    ports:
      - "1883:1883"

  mqtt-broker2:
    build:
      context: .
      dockerfile: Dockerfile-mosquitto
    ports:
      - "1884:1884"

  python-publisher:
    build:
      context: .
      dockerfile: Dockerfile-python
    depends_on:
      - mqtt-broker
  
  python-subscriber:
    build:
      context: .
      dockerfile: Dockerfile-python
    depends_on:
      - mqtt-broker
    

