version: "3"
services:
  mosquitto-1:
    build:
      context: .
      dockerfile: Dockerfile-mosquitto-1
    container_name: mosquitto-1
    ports:
      - "1890:1890"
    volumes:
      - mosquitto-1-data:/mosquitto/data
      - mosquitto-1-log:/mosquitto/log
      - ./mosquitto-1.conf:/mosquitto/config/mosquitto.conf

  python-publisher:
    build:
      context: .
      dockerfile: Dockerfile-publisher
    depends_on:
      - mosquitto-1
  


volumes:
  mosquitto-1-data:
  mosquitto-1-log:



