version: "3"
services:
  mosquitto-1:
    build:
      context: .
      dockerfile: Dockerfile-mosquitto-1
    container_name: mosquitto-1
    ports:
      - "1890:1890"
    volumes:
      - mosquitto-1-data:/mosquitto/data
      - mosquitto-1-log:/mosquitto/log
      - ./mosquitto-1.conf:/mosquitto/config/mosquitto.conf

  mosquitto-2:
    build:
      context: .
      dockerfile: Dockerfile-mosquitto-2
    container_name: mosquitto-2
    ports:
      - "1891:1890"
    volumes:
      - mosquitto-2-data:/mosquitto/data
      - mosquitto-2-log:/mosquitto/log
      - ./mosquitto-2.conf:/mosquitto/config/mosquitto.conf

  python-publisher:
    build:
      context: .
      dockerfile: Dockerfile-publisher
    depends_on:
      - mosquitto-1
      - mosquitto-2

  
  python-subscriber:
    build:
      context: .
      dockerfile: Dockerfile-subscriber
    depends_on:
      - mosquitto-1
      - mosquitto-2
  
volumes:
  mosquitto-1-data:
  mosquitto-1-log:
  mosquitto-2-data:
  mosquitto-2-log:



